# Python, Numpy, and Vectorization

In [1]:
import numpy as np
import time

## Useful References
NumPy Documentation including a basic introduction: <a href="https://numpy.org/doc/stable/">NumPy.org</a> <br>
A challenging feature topic:  <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html">NumPy Broadcasting</a>


## Numpy Arrays
- indexable
- n-dimentional array
- contain elements of the same type ```dtype```
- 1-D array, shape (n, )

## Vector Creation


In [2]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.79214596 0.13873613 0.59441663 0.68272303], a shape = (4,), a data type = float64


some data creation rountines do not take a shape touple

In [5]:
a = np.arange(4.)
b = np.random.rand(4)
a, b

(array([0., 1., 2., 3.]),
 array([0.54908773, 0.41315485, 0.82020921, 0.02063144]))

values can be specified manually as well

## Operations on Vectors
### Single vector operations

In [7]:
a = np.arange(4)
print(f"a             : {a}")

b = -a 
print(f"b = -a        : {b}")

b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [0 1 2 3]
b = -a        : [ 0 -1 -2 -3]
b = np.sum(a) : 6
b = np.mean(a): 1.5
b = a**2      : [0 1 4 9]


### Vector Vector Operations

In [9]:
b = 5 * a
b

array([ 0,  5, 10, 15])

In [10]:
c = np.dot(a, b)
c

70

## Matrix 


In [12]:
a = np.zeros((1, 5))
b = np.random.random_sample((1, 1))
a, b

(array([[0., 0., 0., 0., 0.]]), array([[0.46957528]]))

In [14]:
# reshape is a convenient way to create matrices
a = np.arange(6).reshape(-1, 2)

# -1 means: automatically calculate this array
# 2 means: inner has 2 dim

a

array([[0, 1],
       [2, 3],
       [4, 5]])